# Generated by Django 5.0.6 on 2024-06-04 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Projeto', '0003_aluno_presenca_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Projeto.aluno')),
            ],
            options={
                'unique_together': {('aluno', 'data')},
            },
        ),
    ]
